version: '3.8'
services:
  nest-postgres:
    image: postgres:alpine
    container_name: nest-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - nest-postgres:/var/lib/postgresql/data
    networks:
    - my_network
  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    ports:
      - 5173:5173
    networks:
    - my_network
  backend:
    build: ./backend/
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    networks:
    - my_network
volumes:
  nest-postgres:
    name: nest-postgres-db
networks:
  my_network:
    driver: bridge
