version: '3.8'
services:
  nest-postgres:
    image: postgres:alpine
    container_name: nest-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - nest-postgres:/var/lib/postgresql/data
volumes:
  nest-postgres:
    name: nest-postgres-db
